version: "3.3"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: filatov
      POSTGRES_DB: usof
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
    - '2345:5432'
    volumes:
    - ./src/migrations:/docker-entrypoint-initdb.d
  web:
    build: .
    ports:
    - '5000:5000'
    depends_on:
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'
  react:
    build:
      context: ./usof-frontend
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'








