export const Types = {
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE : 'FETCH_USERS_FAILURE',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    FETCH_REGISTER_SUCCESS: 'FETCH_REGISTER_SUCCESS',
}